// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type UsersTable from './Users';
import type ProjectsTable from './Projects';
import type TodosTable from './Todos';

export default interface PublicSchema {
  users: UsersTable;

  projects: ProjectsTable;

  todos: TodosTable;
}
