// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ProjectsId } from './Projects';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.todos */
export type TodosId = number & { __brand: 'TodosId' };

/** Represents the table public.todos */
export default interface TodosTable {
  id: ColumnType<TodosId, TodosId | null, TodosId | null>;

  title: ColumnType<string, string, string | null>;

  completed: ColumnType<boolean | null, boolean | null, boolean | null>;

  projectid: ColumnType<ProjectsId | null, ProjectsId | null, ProjectsId | null>;
}

export type Todos = Selectable<TodosTable>;

export type NewTodos = Insertable<TodosTable>;

export type TodosUpdate = Updateable<TodosTable>;
